// Import all icons from their organized locations
import { GlobeIcon } from "./tech/globe";
import { EmailIcon } from "./tech/email";
import { FramerMotionIcon } from "./tech/framer-motion";
import { NotionIcon } from "./tech/notion";
import { GoogleDriveIcon } from "./tech/google-drive";

// Import social icons
import LinkedinIcon from "./social/linkedin";
import { XIcon } from "./social/x";
import { YoutubeIcon } from "./social/youtube";
import { WhatsappIcon } from "./social/whatsapp";

// Import from tech folder
import {
  AwsIcon,
  BashIcon,
  BloggerIcon,
  BunIcon,
  CppIcon,
  CanvaIcon,
  ClerkIcon,
  CloudRunIcon,
  CloudflareIcon,
  DrizzleOrmIcon,
  EslintIcon,
  ExpressJsIcon,
  FigmaIcon,
  FirebaseIcon,
  GeminiIcon,
  GithubIcon as GithubTechIcon,
  GitIcon,
  GoIcon,
  JavascriptIcon,
  JqueryIcon,
  JsonIcon,
  LinuxIcon,
  MongodbIcon,
  NestjsIcon,
  NextJsIcon,
  NodeJsIcon,
  NpmIcon,
  OpenaiIcon,
  PostgresqlIcon,
  PostmanIcon,
  PrismaIcon,
  PythonIcon,
  ReactIcon,
  ReactHookFormIcon,
  ReactQueryIcon,
  RedisIcon,
  ShadcnUiIcon,
  StripeIcon,
  SupabaseIcon,
  TailwindCssIcon,
  TurborepoIcon,
  TypescriptIcon,
  VercelIcon,
  VertexAiIcon,
  ViteJsIcon,
  VscodeIcon,
  ZodIcon,
  ZustandIcon,
} from "./tech";

// Import from social folder
import { GithubIcon, InstagramIcon, TwitterIcon } from "./social";

// Re-export individually to maintain previous named exports
export {
  GlobeIcon,
  EmailIcon,
  FramerMotionIcon,
  NotionIcon,
  GoogleDriveIcon,
  LinkedinIcon,
  XIcon,
  YoutubeIcon,
  WhatsappIcon,
  AwsIcon,
  BashIcon,
  BloggerIcon,
  BunIcon,
  CppIcon,
  CanvaIcon,
  ClerkIcon,
  CloudRunIcon,
  CloudflareIcon,
  DrizzleOrmIcon,
  EslintIcon,
  ExpressJsIcon,
  FigmaIcon,
  FirebaseIcon,
  GeminiIcon,
  GithubTechIcon,
  GitIcon,
  GoIcon,
  JavascriptIcon,
  JqueryIcon,
  JsonIcon,
  LinuxIcon,
  MongodbIcon,
  NestjsIcon,
  NextJsIcon,
  NodeJsIcon,
  NpmIcon,
  OpenaiIcon,
  PostgresqlIcon,
  PostmanIcon,
  PrismaIcon,
  PythonIcon,
  ReactIcon,
  ReactHookFormIcon,
  ReactQueryIcon,
  RedisIcon,
  ShadcnUiIcon,
  StripeIcon,
  SupabaseIcon,
  TailwindCssIcon,
  TurborepoIcon,
  TypescriptIcon,
  VercelIcon,
  VertexAiIcon,
  ViteJsIcon,
  VscodeIcon,
  ZodIcon,
  ZustandIcon,
  GithubIcon,
  InstagramIcon,
  TwitterIcon,
};

export type IconProps = React.HTMLAttributes<SVGElement>;

// Export Icons as a namespace object for backward compatibility
export const Icons = {
  github: GithubIcon,
  linkedin: LinkedinIcon,
  x: XIcon,
  youtube: YoutubeIcon,
  email: EmailIcon,
  globe: GlobeIcon,
  instagram: InstagramIcon,
  twitter: TwitterIcon,
  whatsapp: WhatsappIcon,
  framerMotion: FramerMotionIcon,
  notion: NotionIcon,
  googleDrive: GoogleDriveIcon,
  aws: AwsIcon,
  bash: BashIcon,
  blogger: BloggerIcon,
  bun: BunIcon,
  cpp: CppIcon,
  canva: CanvaIcon,
  clerk: ClerkIcon,
  cloudRun: CloudRunIcon,
  cloudflare: CloudflareIcon,
  drizzleOrm: DrizzleOrmIcon,
  eslint: EslintIcon,
  expressJs: ExpressJsIcon,
  figma: FigmaIcon,
  firebase: FirebaseIcon,
  gemini: GeminiIcon,
  githubTech: GithubTechIcon,
  git: GitIcon,
  go: GoIcon,
  javascript: JavascriptIcon,
  jquery: JqueryIcon,
  json: JsonIcon,
  linux: LinuxIcon,
  mongodb: MongodbIcon,
  nestjs: NestjsIcon,
  nextJs: NextJsIcon,
  nodeJs: NodeJsIcon,
  npm: NpmIcon,
  openai: OpenaiIcon,
  postgresql: PostgresqlIcon,
  postman: PostmanIcon,
  prisma: PrismaIcon,
  python: PythonIcon,
  react: ReactIcon,
  reactHookForm: ReactHookFormIcon,
  reactQuery: ReactQueryIcon,
  redis: RedisIcon,
  shadcnUi: ShadcnUiIcon,
  stripe: StripeIcon,
  supabase: SupabaseIcon,
  tailwindCss: TailwindCssIcon,
  turborepo: TurborepoIcon,
  typescript: TypescriptIcon,
  vercel: VercelIcon,
  vertexAi: VertexAiIcon,
  viteJs: ViteJsIcon,
  vscode: VscodeIcon,
  zod: ZodIcon,
  zustand: ZustandIcon,
};
